### ISSUE TITLE
Use EGL_KHR_image_base for sharing the framebuffer.

### ISSUE THREAD

**Issue by degasus** [team-phoenix/phoenix-backend#8]
Shared OpenGL context may lock each other, so it's sometimes faster to go the low-level way with KHR_image_base.

**Comment by athairus** [comment]
Issue moved to [team-phoenix/Phoenix #287](https://github.com/team-phoenix/Phoenix/issues/287) via [**ZenHub.io**](https://www.zenhub.io/)
